name = "gleam_web_server"
version = "1.0.0"

# Required versions and package identifiers
gleam = ">= 1.0.0"

# Set the target to Erlang
target = "erlang"

# Dependencies
[dependencies]
gleam_stdlib = ">= 0.51.0 and < 1.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
wisp = ">= 2.1.0 and < 3.0.0"
mist = ">= 5.0.3 and < 6.0.0"
nakai = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

